-- 内部系统模式（白名单账号 + 设备审批 + 管理员后台RPC + 一人一机：批准即换机）
-- 管理员邮箱（你提供的）
-- 912872499@qq.com

-- 1) 白名单表：只允许表内账号使用
create table if not exists public.allowed_users (
  id bigint generated by default as identity primary key,
  email text not null unique,
  role text not null default 'user', -- 'admin' | 'user'
  enabled boolean not null default true,
  created_at timestamptz not null default now()
);

-- 插入/更新管理员
insert into public.allowed_users (email, role, enabled)
values ('912872499@qq.com','admin',true)
on conflict (email) do update set role=excluded.role, enabled=excluded.enabled;

-- 2) 设备审批表
create table if not exists public.allowed_devices (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  device_token text not null,
  approved boolean not null default false,
  blocked boolean not null default false,
  created_at timestamptz not null default now(),
  last_seen_at timestamptz,
  unique (user_id, device_token)
);

create index if not exists idx_allowed_devices_user on public.allowed_devices(user_id);

-- 3) RLS：普通用户只能申请/查看自己的设备，不能自己审批
alter table public.allowed_devices enable row level security;

do $$
begin
  -- insert policy
  if not exists (select 1 from pg_policies where schemaname='public' and tablename='allowed_devices' and policyname='insert own device') then
    create policy "insert own device"
    on public.allowed_devices for insert
    to authenticated
    with check (auth.uid() = user_id);
  end if;

  -- select policy
  if not exists (select 1 from pg_policies where schemaname='public' and tablename='allowed_devices' and policyname='select own device') then
    create policy "select own device"
    on public.allowed_devices for select
    to authenticated
    using (auth.uid() = user_id);
  end if;
end $$;

-- 4) 管理员判定：通过 JWT email 判断是否管理员
create or replace function public.is_admin()
returns boolean
language sql
stable
as $$
  select exists(
    select 1 from public.allowed_users
    where email = coalesce(auth.jwt()->>'email','')
      and role = 'admin'
      and enabled = true
  );
$$;

-- 5) 管理员后台 RPC：列出设备（带用户邮箱）
create or replace function public.admin_list_devices(limit_count int default 200)
returns table(
  id bigint,
  user_id uuid,
  user_email text,
  device_token text,
  approved boolean,
  blocked boolean,
  created_at timestamptz,
  last_seen_at timestamptz
)
language sql
security definer
set search_path = public, auth
as $$
  select d.id, d.user_id, u.email as user_email, d.device_token, d.approved, d.blocked, d.created_at, d.last_seen_at
  from public.allowed_devices d
  join auth.users u on u.id = d.user_id
  order by d.created_at desc
  limit greatest(1, least(limit_count, 500));
$$;

-- 6) 管理员批准（方案2：批准即换机，自动封禁同账号旧设备）
create or replace function public.admin_approve_device(p_device_id bigint)
returns void
language plpgsql
security definer
set search_path = public, auth
as $$
declare
  v_user uuid;
begin
  if not public.is_admin() then
    raise exception 'not admin';
  end if;

  select user_id into v_user from public.allowed_devices where id = p_device_id;
  if v_user is null then
    raise exception 'device not found';
  end if;

  -- 封掉旧设备（同账号其它设备）
  update public.allowed_devices
     set blocked = true, approved = false
   where user_id = v_user
     and id <> p_device_id;

  -- 放行新设备
  update public.allowed_devices
     set approved = true, blocked = false
   where id = p_device_id;
end;
$$;

-- 7) 管理员封禁
create or replace function public.admin_block_device(p_device_id bigint)
returns void
language plpgsql
security definer
set search_path = public, auth
as $$
begin
  if not public.is_admin() then
    raise exception 'not admin';
  end if;

  update public.allowed_devices
     set blocked = true, approved = false
   where id = p_device_id;
end;
$$;

-- 授权执行 RPC 给已登录用户（内部后台是网页端调用）
grant execute on function public.is_admin() to authenticated;
grant execute on function public.admin_list_devices(int) to authenticated;
grant execute on function public.admin_approve_device(bigint) to authenticated;
grant execute on function public.admin_block_device(bigint) to authenticated;

-- 8) 建议：Authentication -> URL Configuration
-- Site URL / Redirect URLs 设置为：https://www.liruna.icu
